# Permalinks
permalink:           none

# Setup
title:               Maker
tagline:             Whitepaper
url:                 https://makerdao.github.io/docs
paginate:            1
baseurl:             https://makerdao.github.io/docs

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed




# navigation
navigation:

 - title: Introduction to Maker
   url: /

# About/contact
author:
  name:              Rune Christensen
  url:               https://twitter.com/makerdao
  email:             rune@makedao.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/makerdao/docs




markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)




gems:
  - jekyll-mentions
  - jekyll-sitemap
  - github-pages
  - jekyll-paginate
